export const AUTHORS_DATA_FETCHING = 'AUTHORS_DATA_FETCHING';

export const INPUT_CHANGE = 'INPUT_CHANGE';

export const TOGGLE_PAGEVIEWS = 'TOGGLE_PAGEVIEWS';

export const TOGGLE_PUBLICATIONS = 'TOGGLE_PUBLICATIONS';

export const SORT_PAGEVIEW_DOWN = 'SORT_PAGEVIEW_DOWN';

export const SORT_PAGEVIEW_UP = 'SORT_PAGEVIEW_UP';

export const SORT_PUBLICATIONS_DOWN = 'SORT_PUBLICATIONS_DOWN';

export const SORT_PUBLICATIONS_UP = 'SORT_PUBLICATIONS_UP';

export const FIND_LEADERS = 'FIND_LEADERS';

export const NEXT_PAGE = 'NEXT_PAGE';

export const PREV_PAGE = 'PREV_PAGE';


